language: java

jdk:
  - oraclejdk8

install: 
  - travis_wait mvn install -Pdistribution -DskipTests=true -B -V -q

script:
  - mvn test -B
  - mvn -file testsuite/integration-arquillian test -B -Pno-console

sudo: false
