name: Keycloak CI

on:
  push:
    branches-ignore: [main]
  # as the ci.yml contains actions that are required for PRs to be merged, it will always need to run on all PRs
  pull_request: {}
  schedule:
    - cron: '0 20,23,2,5 * * *'
  workflow_dispatch:

env:
  DEFAULT_JDK_VERSION: 11
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

#concurrency:
#  # Only cancel jobs for new commits on PRs, and always do a complete run on other branches (e.g. `main`).
#  # See: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
#  group: keycloak-ci-${{ github.head_ref || github.run_id }}
#  cancel-in-progress: true

jobs:
  build:
    name: Build
    if: ${{ ( github.event_name != 'schedule' ) || ( github.event_name == 'schedule' && github.repository == 'keycloak/keycloak' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
          cache: 'maven'
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Build Keycloak
        run: |
           ./mvnw clean install -nsu -B -e -DskipTests -Pdistribution
           ./mvnw clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-quarkus

      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-artifacts.zip
          retention-days: 1
          path: |
            ~/.m2/repository/org/keycloak
            !~/.m2/repository/org/keycloak/**/*.tar.gz

      - name: Remove keycloak artifacts before caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm -rf ~/.m2/repository/org/keycloak

  ### Tests: Quarkus distribution

  quarkus-tests:
    name: Quarkus Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 115
    env:
      MAVEN_OPTS: -Xmx1024m
    strategy:
      fail-fast: false
      matrix:
        test-run: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
          cache: 'maven'
      - name: Cleanup org.keycloak artifacts
        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true

      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v3
        with:
          path: ~/.m2/repository/org/keycloak/
          name: keycloak-artifacts.zip
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Prepare the local distribution archives
        run: ./mvnw clean install -DskipTests -Pdistribution

      - name: Run Quarkus Integration Tests
        run: |
          ./mvnw clean install -nsu -B -f quarkus/tests/pom.xml -Dtest=HostnameDistTest
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip -q reports-quarkus-tests.zip -@
          exit $TEST_RESULT

      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1.3.0
        if: always() && github.repository == 'keycloak/keycloak'
        with:
          api_key: ${{ secrets.FORESIGHT_API_KEY }}
          test_format: JUNIT
          test_framework: JUNIT
          test_path: 'quarkus/tests/integration/target/surefire-reports/*.xml'

      - name: Quarkus test reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: reports-quarkus-tests
          retention-days: 14
          path: reports-quarkus-tests.zip
          if-no-files-found: ignore

# NOTE: WebAuthn tests can be enabled once the issue #12621 is resolved
#
#  webauthn-test:
#    name: WebAuthn Tests
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 2
#
#      - name: Check whether this phase should run
#        run: echo "GIT_DIFF=$[ $( git diff --name-only HEAD^ | egrep -ic 'webauthn|passwordless' ) ]" >> $GITHUB_ENV
#
#      - uses: actions/setup-java@v1
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        with:
#          java-version: ${{ env.DEFAULT_JDK_VERSION }}
#
#      - name: Update maven settings
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/
#
#      - name: Cache Maven packages
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#          restore-keys: cache-1-${{ runner.os }}-m2
#
#      - name: Cleanup org.keycloak artifacts
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true
#
#      - name: Download built keycloak
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        id: download-keycloak
#        uses: actions/download-artifact@v2
#        with:
#          path: ~/.m2/repository/org/keycloak/
#          name: keycloak-artifacts.zip
#
#      - name: Run WebAuthn tests
#        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
#        run: |
#          mvn clean install -nsu -B -Dbrowser=chrome -Pwebauthn -f testsuite/integration-arquillian/tests/other/pom.xml -Dtest=org.keycloak.testsuite.webauthn.**.*Test | misc/log/trimmer.sh
#
#          TEST_RESULT=${PIPESTATUS[0]}
#          find . -path '*/target/surefire-reports/*.xml' | zip -q reports-webauthn-tests.zip -@
#          exit $TEST_RESULT
#
#      - name: WebAuthn test reports
#        uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: reports-webauthn-tests
#          retention-days: 14
#          path: reports-webauthn-tests.zip
#          if-no-files-found: ignore
