name: IPv6 Playground

on:
  push:
  workflow_dispatch:

jobs:

  build:
    name: tmate
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3